# Generated by Django 5.1.4 on 2025-09-30 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_review_createat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='createAt',
            new_name='createdAt',
        ),
    ]
